### ISSUE TITLE
Differences between the first three downstream tasks?(except for the dataset)

### ISSUE THREAD

**Issue by aestheticisma** [agemagician/CodeTrans#5]
Hi, I have a question and want to know the difference between these three tasks: code documentation generate、code summarization and code comment generate. My understanding is that all three of these tasks are generating natural language
descriptions for a code snippet.

**Comment by agemagician** [comment]
Hi,

The output of these three tasks is the same as you mentioned, but the input is different.

Input Code Level:
Code Documentation Generation: A complete function.
Code summarization: A shortcode snippet.
Code Comment Generation: A complete function.

Input Languages:
Code Documentation Generation: Python, Java, Go, Php, Ruby, and Javascript.
Code summarization: Python, C#, and SQL.
Code Comment Generation: Java.

Input source:
Code Documentation Generation: GitHub.
Code summarization: StackOverflow.
Code Comment Generation: GitHub.

Please, refer to the paper for more information:
https://arxiv.org/abs/2104.02443
