### ISSUE TITLE
summary model outputs interrogative sentence？

### ISSUE THREAD

**Issue by estella98** [agemagician/CodeTrans#8]
Hi, When playing with the example notebook provided in the following link: https://github.com/agemagician/CodeTrans/blob/main/prediction/single%20task/source%20code%20summarization/python/base_model.ipynb
I noticed the summary is an interrogative sentence. 
![image](https://user-images.githubusercontent.com/36647501/169199816-20f2ba97-6791-4680-ad52-a164bc70623f.png)

But it seems like when the example was first created, the expected output should be a declarative sentence as follow:
![image](https://user-images.githubusercontent.com/36647501/169199769-d84efd85-728f-476f-977f-a6746b2a315d.png)

Has the model been updated recently so that it outputs summary differently?

Thank you!

**Comment by agemagician** [comment]
Hi,

We didn't update/change the model. However, the transformers library code changed which is now producing different results.
To get the same results you need to install an older version of the transformers library:

`!pip install -q -U transformers==4.1.0 sentencepiece`
